name: Build all configurations and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  build-and-publish:
    permissions: 
      contents: read
      packages: write
    runs-on: ubuntu-latest
    strategy:
        matrix:
          java: [ '8' ]

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Set settings.xml
        uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
              "id": "uvl-emr-github-lime-emr",
              "username": "${{ secrets.MAVEN_GITHUB_ACTIONS_DEPLOY_USERNAME }}",
              "password": "${{ secrets.MAVEN_GITHUB_ACTIONS_DEPLOY_TOKEN }}"
            }]
  
      - name: Build and Test
        run: mvn --batch-mode --update-snapshots --activate-profiles validator clean package

      - name: Publish UVL distro artifacts to GitHub
        uses: ./.github/actions/upload-maven-artifacts
        with:
          artifact-name: "distro"
          artifact-path: "${{ github.workspace }}/distro"
          maven-server-username: "${{ secrets.MAVEN_GITHUB_ACTIONS_DEPLOY_USERNAME }}"
          maven-server-token: "${{ secrets.MAVEN_GITHUB_ACTIONS_DEPLOY_TOKEN }}"
          
      - name: Publish UVL Mugamba to artifacts GitHub
        uses: ./.github/actions/upload-maven-artifacts
        with:
          artifact-name: "Burundi"
          artifact-path: "${{ github.workspace }}/countries/burundi"
          maven-server-username: "${{ secrets.MAVEN_GITHUB_ACTIONS_DEPLOY_USERNAME }}"
          maven-server-token: "${{ secrets.MAVEN_GITHUB_ACTIONS_DEPLOY_TOKEN }}"

      - name: Publish UVL Burundi artifacts to GitHub
        uses: ./.github/actions/upload-maven-artifacts
        with:
          artifact-name: "Mugamba"
          artifact-path: "${{ github.workspace }}/sites/mugamba"
          maven-server-username: "${{ secrets.MAVEN_GITHUB_ACTIONS_DEPLOY_USERNAME }}"
          maven-server-token: "${{ secrets.MAVEN_GITHUB_ACTIONS_DEPLOY_TOKEN }}"

  release:
    if: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'release' }}    
    runs-on: ubuntu-latest 
    needs: build
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v4
        with:
            clean: false
      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Set settings.xml
        uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
              "id": "msf-ocg-github-lime-emr",
              "username": "${{ secrets.MAVEN_GITHUB_ACTIONS_DEPLOY_USERNAME }}",
              "password": "${{ secrets.MAVEN_GITHUB_ACTIONS_DEPLOY_TOKEN }}"
            }]

      - name: Publish maven artifacts
        run: 'mvn --batch-mode deploy'
        working-directory: ${{ github.workspace }}/omod